// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        int32            `json:"id"`
	StartTime pgtype.Timestamp `json:"startTime"`
	EndTime   pgtype.Timestamp `json:"endTime"`
	Duration  pgtype.Interval  `json:"duration"`
	Tags      []string         `json:"tags"`
}
