// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: pkg/serdes/proto/data.proto

package compiled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PomoSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkDuration  *durationpb.Duration `protobuf:"bytes,2,opt,name=work_duration,json=workDuration,proto3" json:"work_duration,omitempty"`
	BreakDuration *durationpb.Duration `protobuf:"bytes,3,opt,name=break_duration,json=breakDuration,proto3" json:"break_duration,omitempty"`
	Tags          []string             `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *PomoSession) Reset() {
	*x = PomoSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_serdes_proto_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PomoSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PomoSession) ProtoMessage() {}

func (x *PomoSession) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_serdes_proto_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PomoSession.ProtoReflect.Descriptor instead.
func (*PomoSession) Descriptor() ([]byte, []int) {
	return file_pkg_serdes_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *PomoSession) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PomoSession) GetWorkDuration() *durationpb.Duration {
	if x != nil {
		return x.WorkDuration
	}
	return nil
}

func (x *PomoSession) GetBreakDuration() *durationpb.Duration {
	if x != nil {
		return x.BreakDuration
	}
	return nil
}

func (x *PomoSession) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PomoSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sessions []*PomoSession `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
}

func (x *PomoSessions) Reset() {
	*x = PomoSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_serdes_proto_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PomoSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PomoSessions) ProtoMessage() {}

func (x *PomoSessions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_serdes_proto_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PomoSessions.ProtoReflect.Descriptor instead.
func (*PomoSessions) Descriptor() ([]byte, []int) {
	return file_pkg_serdes_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *PomoSessions) GetSessions() []*PomoSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_pkg_serdes_proto_data_proto protoreflect.FileDescriptor

var file_pkg_serdes_proto_data_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x64, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73,
	0x65, 0x72, 0x64, 0x65, 0x73, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x50, 0x6f, 0x6d, 0x6f, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x0e, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x5f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x3f, 0x0a, 0x0c, 0x50,
	0x6f, 0x6d, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x65, 0x72, 0x64, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x6d, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_serdes_proto_data_proto_rawDescOnce sync.Once
	file_pkg_serdes_proto_data_proto_rawDescData = file_pkg_serdes_proto_data_proto_rawDesc
)

func file_pkg_serdes_proto_data_proto_rawDescGZIP() []byte {
	file_pkg_serdes_proto_data_proto_rawDescOnce.Do(func() {
		file_pkg_serdes_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_serdes_proto_data_proto_rawDescData)
	})
	return file_pkg_serdes_proto_data_proto_rawDescData
}

var file_pkg_serdes_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_serdes_proto_data_proto_goTypes = []interface{}{
	(*PomoSession)(nil),         // 0: serdes.PomoSession
	(*PomoSessions)(nil),        // 1: serdes.PomoSessions
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_pkg_serdes_proto_data_proto_depIdxs = []int32{
	2, // 0: serdes.PomoSession.work_duration:type_name -> google.protobuf.Duration
	2, // 1: serdes.PomoSession.break_duration:type_name -> google.protobuf.Duration
	0, // 2: serdes.PomoSessions.sessions:type_name -> serdes.PomoSession
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_serdes_proto_data_proto_init() }
func file_pkg_serdes_proto_data_proto_init() {
	if File_pkg_serdes_proto_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_serdes_proto_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PomoSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_serdes_proto_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PomoSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_serdes_proto_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_serdes_proto_data_proto_goTypes,
		DependencyIndexes: file_pkg_serdes_proto_data_proto_depIdxs,
		MessageInfos:      file_pkg_serdes_proto_data_proto_msgTypes,
	}.Build()
	File_pkg_serdes_proto_data_proto = out.File
	file_pkg_serdes_proto_data_proto_rawDesc = nil
	file_pkg_serdes_proto_data_proto_goTypes = nil
	file_pkg_serdes_proto_data_proto_depIdxs = nil
}
